DROP table IF EXISTS `POJO_DOMAIN` CASCADE;
DROP database IF EXISTS dbname;

CREATE DATABASE IF NOT EXISTS dbname;
USE dbname;

CREATE TABLE IF NOT EXISTS `POJO_DOMAIN` (
  `POJO_ID` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NAME` VARCHAR(255) NOT NULL
);

INSERT INTO POJO_DOMAIN (POJO_ID, NAME) VALUES (1, 'test');
INSERT INTO POJO_DOMAIN (POJO_ID, NAME) VALUES (2, 'sample');